from dotenv import load_dotenv
from urllib.parse import quote
from os import getenv

load_dotenv()

# # CHAVE SECRETA DA API
SECRET_KEY = getenv('SECRET_KEY', 'eb5Cpp1V9S14mz7kwH5eT6p7cgQR1I0D')
# ENDERECO DO HOST DO BANCO
DB_HOST = getenv('DB_HOST', '148.230.77.239')
# PORTA DO BANCO
DB_PORT = getenv('DB_PORT', 3306)
# SCHEMA DO BANCO
DB_SCHEMA = getenv('DB_SCHEMA', 'usuarios')
# USUARIO DO BANCO
DB_USER = getenv('DB_USER', 'user_test')
# SENHA DO BANCO
DB_PASSWORD = getenv('DB_PASSWORD', 'eb5Cpp1V9S14mz7kwH5eT6p7cgQR1I0D')
DB_PASSWORD = quote(DB_PASSWORD)
# DESATIVA A VERIFICAÃO DE CERTIFICADOS DO BANCO
SSL_VERIFY_CERT = getenv('SSL_VERIFY_CERT', 'false')
# STRING DE CONEXÃO DO BANCO
SQLALCHEMY_DATABASE_URI = f'mysql+mysqlconnector://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_SCHEMA}\
    ?ssl_verify_cert={SSL_VERIFY_CERT}'

FLASK_DEBUG=False
SQLALCHEMY_TRACK_MODIFICATIONS=False
TRAP_HTTP_EXCEPTIONS=False
TRAP_BAD_REQUEST_ERRORS=False
TRAP_HTTP_EXCEPTIONS=False
PROPAGATE_EXCEPTIONS=True

SQLALCHEMY_ECHO=False


